---
all:
  children:
    routers:
      hosts:
        R1:
        R2:


# seperating variables from inventory files help modular project
# This yaml inventory format is equivalent to the hosts file for ansible = more programmatic, intuitve, organized and suited for hierarchy
# INI format = useful when hosts are in many groups
# [routers]
# R1
# R2