# Ansible Hosts File
---
all:
  children:
    routers:
      children:
        ios_routers:
          hosts:
            R1: 
              ansible_host: 172.16.1.1
            R2:
              ansible_host: 172.16.2.1
            R3:
              ansible_host: 172.16.3.1
            R4:
              ansible_host: 172.16.4.1
        iosxr_routers:
          hosts:
            R5:
              ansible_host: "To be filled in"
              



# seperating variables from inventory files help modular project
# This yaml inventory format is equivalent to the hosts file for ansible = more programmatic, intuitve, organized and suited for hierarchy
# INI format = useful when hosts are in many groups
# [routers]
# R1 ansible_host: 172.16.1.1
# R2 ""
# R3 ""
# R4 ""