---
- name: "Play 1: Configuring Routers with ios_config module and jinja2"
  hosts: routers
  connection: network_cli

  tasks:
    # configure all router with hostname stated in host_vars folder
    - name: "Task 1: Updating router names"
      ios_config: 
        lines: hostname {{ hostname.name }}

    # configure all router with eigrp stated in host_vars folder
    - name: "Task 2: Applying eigrp"
      ios_config:
        src: "templates/eigrp.j2"
        save_when: changed
      notify: config_changed
      register: cli_result

  # This will print changes only if it is not present, otherwise, nothing will be printed. (Idempotent)
  handlers:
    - name: "Handler 1: Displaying changes"
      listen: config_changed
      debug:
        # prints out the commands that were added to the configs
        msg: "{{ cli_result.commands }}"
      
        
